import { Products } from "../interfaces/Products";

export const listProducts: Products[] = [
    {
      img: "/assets/images/product-1.png",
      title: "Spy x Family Tshirt",
      location: "North Purwokerto",
      rating: 4.8,
      price: 26,
      totalSold: 1.238,
    },
    {
      img: "/assets/images/product-2.png",
      title: "Green Man Jacket",
      location: "North Purwokerto",
      rating: 4.8,
      price: 49,
      totalSold: 1.238,
    },
    {
      img: "/assets/images/product-3.png",
      title: "Iphone 14 Pro Max",
      location: "North Purwokerto",
      rating: 4.8,
      price: 1200,
      totalSold: 1.238,
    },
    {
      img: "/assets/images/product-4.png",
      title: "Oversized Tshirt",
      location: "North Purwokerto",
      rating: 4.8,
      price: 48,
      totalSold: 1.238,
    },
    {
      img: "/assets/images/product-5.png",
      title: "Brown Woman Jacket",
      location: "North Purwokerto",
      rating: 4.8,
      price: 49,
      totalSold: 1.238,
    },
    {
      img: "/assets/images/product-6.png",
      title: "Airpod Pro 2022",
      location: "North Purwokerto",
      rating: 4.8,
      price: 459,
      totalSold: 1.238,
    },
    {
      img: "/assets/images/product-7.png",
      title: "DJI Mini 3 Pro",
      location: "North Purwokerto",
      rating: 4.8,
      price: 824,
      totalSold: 1.238,
    },
    {
      img: "/assets/images/product-8.png",
      title: "Ipad Pro Gen 3",
      location: "North Purwokerto",
      rating: 4.8,
      price: 1200,
      totalSold: 1.238,
    },
  ];